spring: 
  profiles:
    active:
       -dev
---
spring: 
  profiles: dev
    application:
       name: microservicecloud-config-zxb-dev
---
spring: 
  profiles: test
    application:
       name: microservicecloud-config-zxb-test

